@extends('layout.master')

@section('content')

<link rel='stylesheet' id='twentytwelve-style-css'  href='http://www.spelregels.info/wp-content/themes/twentytwelve/style.css?ver=4.7.11' type='text/css' media='all' />

    <div id="content" role="main" class="jumbotron">
        <article id="post-287" class="post-287 page type-page status-publish hentry">
            <header class="entry-header">
                <h1 class="entry-title">Spelregels Carcassonne</h1>
            </header>
            <div class="entry-content">
                <div class="top-left lft" data-id="287">
                </div>
                <!-- kk-star-ratings -->
                <h1 align="LEFT">Carcassonne</h1>
                <p>2 tot 5 spelers vanaf 10 jaar. <a href="http://www.spelregels.info/wp-content/uploads/2013/02/carcassonne-game1.jpg"><img class="size-full wp-image-519 alignright" alt="carcassonne-game1" src="http://www.spelregels.info/wp-content/uploads/2013/02/carcassonne-game1.jpg" width="151" height="220" srcset="http://www.spelregels.info/wp-content/uploads/2013/02/carcassonne-game1.jpg 400w, http://www.spelregels.info/wp-content/uploads/2013/02/carcassonne-game1-205x300.jpg 205w" sizes="(max-width: 151px) 100vw, 151px" /></a></p>
                <p align="LEFT">De Zuid-Franse stad Carcassonne is beroemd door haar unieke vestingen uit de tijd van de Romeinen en de Ridders. De spelers proberen met hun &#8216;volgelingen&#8217; op de straten en in de stad, op de weiden en in de kloosters in de omgeving van Carcassonne hun geluk te vinden. De uitbouw van die wijde omgeving ligt in hun handen. Door het gepast inzetten van hun volgelingen als handelsreizigers, ridders, boeren of monniken effenen ze hun weg naar succes. Hieronder de spelregels.</p>
                <p>Spelmateriaal:<br />
                    ·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">72 landschapskaarten (waarvan 1 startkaart met een donkere rugzijde) &#8211; Deze kaartjes bevatten stadsdelen, straatdelen, kruispunten, weilanden en/of kloosters. </span></span></p>
                <p align="LEFT">·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">40 &#8216;volgelingen&#8217; (telkens 8 per kleur) &#8211; Elke figuur kan als ridder, handelsreiziger, boer of monnik ingezet worden. Één van de figuren wordt op de puntentabel gebruikt.</span></span></p>
                <p align="LEFT">·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">1 waarderingstabel &#8211; Deze geeft op elk moment de &#8216;tussenstand&#8217; aan.</span></span></p>
                <p style="text-align: left;">Doel:<br/>
                    De spelers bouwen samen om de beurt het landschap uit door het aanleggen van een landschapskaartje. Zo ontstaan er een aaneengesloten stratennet, steden, weidelandschappen en kloosters waarop de spelers hun volgelingen kunnen plaatsen om zodoende punten te verzamelen. Daar men zowel tijdens het spel als na afloop ervan punten kan scoren, staat pas na de eindtelling de winnaar vast.<br />
                    <br>
                    Voorbereiding:<a href="http://www.spelregels.info/wp-content/uploads/2013/02/carcassonne.jpg"><img class="size-full wp-image-518 alignright" alt="carcassonne" src="http://www.spelregels.info/wp-content/uploads/2013/02/carcassonne.jpg" width="264" height="150" /></a><br />
                    ·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">De startkaart wordt open in het midden van de tafel gelegd.</span></span></p>
                <p align="LEFT">·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">De resterende kaartjes worden geschud en in meerdere verdekte stapeltjes verdeeld.</span></span></p>
                <p align="LEFT">·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">De waarderingstabel wordt aan de rand van het speelveld gelegd.</span></span></p>
                <p align="LEFT">·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Elke speler ontvangt 8 volgelingen van eenzelfde kleur en plaatst één daarvan op het </span></span>startveld <span style="font-size: small;">van de puntentabel. De overblijvende 7 figuren worden voor de speler op de tafel klaargezet.</span></p>
                <p align="LEFT">·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">De jongste speler begint.</span></span></p>
                <p>Spelverloop:<br />
                    Er wordt in wijzerzin gespeeld. Wie aan de beurt is, voert onderstaande acties in de opgegeven volgorde uit:</p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">1. De speler moet een kaartje van een stapel nemen en aanleggen.</span></span></p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">2. De speler mag een eigen volgeling uit zijn voorraad nemen en op het door hem </span></span>gelegde kaartje plaatsen.</p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">3. Worden er door het aanleggen van dat kaartje straten, steden of kloosters afgesloten, </span></span>dan moeten deze aansluitend gewaardeerd worden.</p>
                <p>&nbsp;</p>
                <p align="LEFT">1. Het leggen van een landschapskaartje:</p>
                <p>·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Als eerste actie moet een speler een kaartje van een verdekte stapel nemen en open voor zich neerleggen en dit zo dat iedereen het kaartje kan bekijken. Hierdoor kunnen alle medespelers de speler aan beurt &#8216;goede raad&#8217; meegeven&#8230;</span></span></p>
                <p align="LEFT">·<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Daarna moet de speler dat kaartje bij de reeds geplaatste kaartjes aanleggen. Daarbij gelden de volgende eenvoudige regels:</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">De nieuwe kaart moet met minstens één zijde aan één (of meerdere) reeds aanwezig kaartje(s) grenzen.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Alle getekende weiden, straten en stadsdelen moeten voortgezet worden en dus &#8216;passen&#8217; aan hun buurkaartjes. (Voorbeelden: zie p. 2 bovenaan.</span></span></p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">In het zeldzame geval dat een speler het getrokken kaartje niet kan aanleggen, wordt dit uit het spel genomen en mag die speler een nieuw kaartje trekken en leggen.</span></span></p>
                <p>&nbsp;</p>
                <p align="LEFT">2. Het inzetten van een volgeling:</p>
                <p><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Na het aanleggen, mag een speler nog één volgeling inzetten. Hij moet daarbij op het volgende letten:</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Per beurt mag slechts één volgeling ingezet worden.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">De volgeling moet uit de eigen voorraad genomen worden.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">De volgelling kan alleen op het laatst aangelegde kaartje ingezet worden.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">De speler moet duidelijk kiezen en aangeven op welke deel van het kaartje hij de volgeling plaatst. Hij heeft daarbij de volgende mogelijkheden:</span></span></p>
                <p align="LEFT">§i<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">n een stadsdeel = ridder</span></span></p>
                <p align="LEFT">§<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">op een wegdeel = handelsreiziger</span></span></p>
                <p align="LEFT">§<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">op een weiland = boer</span></span></p>
                <p align="LEFT">§<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">op een klooster = monnik.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Belangrijkste regel: De volgeling kan enkel geplaatst worden in een &#8216;deel&#8217; waar nog geen enkele andere figuur (eigen of vreemde) aanwezig is. Hiervoor moet elk mogelijk deel waarvoor gekozen kan worden bekeken worden in aansluiting met de reeds aanwezige en aangrenzende kaartjes. Aaneengesloten wegstukken, stadsdelen of weilanden vormen daarbij telkens samen één deel. </span></span></p>
                <p>&nbsp;</p>
                <p align="LEFT">voorbeeld 1 &#8211;  Speler blauw kan enkel zijn figuur als &#8216;boer&#8217; inzetten. Het stadsdeel op zijn kaartje is nl. verbonden met het stadsdeel op het aangrenzende kaartje waarop reeds een rode &#8216;ridder&#8217; staat. De weide is daarentegen nog met geen enkele andere weide verbonden.</p>
                <p>voorbeeld 2 &#8211;  De rode speler creëert door het aanleggen een groot aaneengesloten weiland. In dat weiland staat (drie kaartjes verder) reeds een rode figuur. Hierdoor kan rood geen nieuwe &#8216;boer&#8217; meer plaatsen. Hij heeft wel nog de keuze op een figuur als &#8216;ridder&#8217; (in het stadsdeel), als handelsreiziger (op de weg) of als &#8216;boer&#8217; op het apart begrensde weiland te plaatsen.</p>
                <p><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Heeft een speler na verloop van tijd geen figuren meer in zijn voorraad, dan kan hij enkel nog kaartjes aanleggen. Door &#8216;gepast&#8217; inzetten zal hij later zijn ingezette figuren wel terug krijgen en kan ze dan opnieuw inzetten.</span></span></p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Hierna is in de meeste gevallen de volgende speler aan de beurt.</span></span></p>
                <p align="LEFT">Uitzondering: Is door het aanleggen van het kaartje een weg afgesloten, een stad volledig ommuurd of een klooster volledig omringd door kaartjes, dan volgt eerst een tussenwaardering.</p>
                <p>3. Tussentijdse puntentellingen:</p>
                <p>De punten van elke tussentijdse waardering worden onmiddellijk op het scoretabel aangebracht. Daarna worden de figuren die gewaardeerd werden van het speelveld weggenomen en terug aan hun eigenaar gegeven. Deze kan ze dan op een later ogenblik terug inzetten.</p>
                <p>a) een afgesloten straat</p>
                <p><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Een straat is volledig afgesloten als hij aan beide zijden door een stadsdeel, een kruispunt of een klooster is begrensd. Voor een afgewerkte straat ontvangt de speler die op het afgesloten gedeelte een handelsreiziger had staan, evenveel punten als de lengte van de straat. Dit komt overeen met het aantal kaartjes waaruit de straat is opgebouwd. </span></span></p>
                <p>b) een ommuurde stad</p>
                <p><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Een stad is afgewerkt als deze volledig door muren is omringd en er geen hiaten meer </span></span>aanwezig zijn. <span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Voor een afgewerkte stad ontvangt de speler die in die stad een ridder had staan 2 punten voor elk stadsdeel (= aantal kaartjes). Daarenboven brengt elk wapenschild eveneens 2 punten extra op.</span></span></p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Enige uitzondering: een &#8216;kleine&#8217; afgewerkte stad van twee kaartjes, brengt slechts 2 punten op!</span></span></p>
                <p align="LEFT">Opmerkingen:</p>
                <p align="LEFT">1) Wat gebeurt er als er meerdere figuren op eenzelfde afwerkte straat staan of in eenzelfde stad voorkomen? Als gevolg van het aanleggen van kaartjes kan het voorkomen dat meerdere figuren op dezelfde straat of in dezelfde stad terechtkomen. In dit geval gaan de punten enkel naar de speler met de meeste figuren. Bij gelijkheid, krijgen beide spelers de volledige puntenwaarde.</p>
                <p align="LEFT">2) Het is perfect mogelijk dat in eenzelfde beurt iemand een figuur inzet en dit onmiddellijk aanleiding geeft tot een waardering waardoor hij de ingezette figuur direct terugkrijgt.</p>
                <p align="LEFT">3) een afgewerkt klooster</p>
                <p><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Een klooster wordt gewaardeerd als het betreffende kaartje door 8 andere kaartje is omringd en daardoor in het midden van een vierkant van 9 kaartjes ligt. De speler die op het klooster een monnik had staan, ontvangt nu 9 punten.</span></span><br />
                <p align="LEFT">4) weiland</p>
                <p><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Weiland wordt nooit tussentijds gewaardeerd. Figuren die als &#8216;boer&#8217; ingezet worden, blijven dan ook steeds tot het einde van het spel staan! Pas dan brengen ze eventueel punten op.</span></span></p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Meerdere aan elkaar grenzende weiden worden steeds samen als een weidelandschap aanzien. Dit wordt enkel begrensd door straten, stadsmuren of de rand van het speelveld. Door het aanleggen van kaartjes kunnen meerdere boeren binnen eenzelfde weidelandschap terecht komen! Speler moeten dit heel goed in de gaten houden!</span></span></p>
                <p>Speleinde en puntentelling:</p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Het spel eindigt na de beurt waarin het laatste kaartje werd aangelegd. Daarna volgt de slotwaardering.</span></span><a href="http://www.spelregels.info/wp-content/uploads/2013/02/carcassonne-game1.jpg"><img class="size-full wp-image-293 alignright" alt="carcassonne-game1" src="http://www.spelregels.info/wp-content/uploads/2013/02/carcassonne-game1.jpg" width="207" height="270" /></a></p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Eerst worden alle onvolledige straten, steden en kloosters bekeken.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Een straat brengt evenveel punten op als kaartjes waardoor hij is opgebouwd.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Een stad brengt per stadsdeel en per wapenschild 1 punt op.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Een klooster brengt evenveel punten op als kaartjes waaruit het betreffende vierkant bestaat.</span></span></p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Gewaardeerde figuren worden onmiddellijk weggenomen om latere verwarring te vermijden.</span></span></p>
                <p align="LEFT"><span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Aansluitend worden de boeren gewaardeerd. Zij staan nl. in voor de voorzieningen van een stad en worden daarvoor beloond.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Boeren voorzien enkel volledig ommuurde steden. Alleen zij leveren dus punten op.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Het weidelandschap waarin de &#8216;verzorgende&#8217; boer staat, moet aan die stad grenzen. De afstand van de boer naar die stad speelt daarbij geen enkele rol.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Voor elke stad die een boer &#8216;voorziet&#8217;, ontvangt hij 4 punten. Dit puntenaantal is onafhankelijk van de stadsgrootte.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Eenzelfde boer kan meerdere steden in hun noden voorzien en krijgt dan per stad 4 punten.</span></span></p>
                <p align="LEFT">-<span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;">Een stad grenst meestal aan meerdere weidelandschappen tegelijk. In die gevallen moeten alle &#8216;aangrenzende&#8217; boeren in rekening gebracht worden. Enkel de speler die de meeste boeren deed aangrenzen, krijgt de 4 punten. Bij gelijkheid ontvangen alle betrokken spelers 4 punten.</span></span></p>
                <p>voorbeeld 1 &#8211;  De stad grenst aan drie weidelandschappen. Daarbinnen staan samen 2 blauwe en één rode boer. Blauw krijgt de 4 punten.</p>
                <p>voorbeeld 2 &#8211; (rechterfiguur) Aan de kleine stad grenzen twee weidelandschappen. In het ene staat een rode boer in het andere een blauwe boer. Beide spelers krijgen 4 punten voor die stad. Aan de grote stad grenzen eveneens 2 weidelandschappen. In elk van die landschappen staat een blauwe boer. Blauw ontvangt nog eens 4 punten. (Niet dubbel tellen!)<br />
                    <p>&nbsp</p>
                <span style="font-family: Arial; font-size: small;"><span style="font-family: Arial; font-size: small;"><strong>Winnaar: De speler met de meeste punten wint dit spel.</strong></span></span></p>
            </div><!-- .entry-content -->
        </article><!-- #post -->
    </div><!-- #content -->
@endsection